### ISSUE TITLE
b4a deploy after Finished uploading files i am getting error 500

### ISSUE THREAD

**Issue by jakjothi** [back4app/parse-cli-server#20]
parse: error with status=500 and body="Error: Object {&quot;folder&quot;:&quot;cloud&quot;,&quot;filename&quot;:&quot;accurate_background.js&quot;,&quot;version&quot;:&quot;2&quot;,&quot;checksum&quot;:&quot;72dc1d6094ed88d2eae4b9c2d23749b6&quot;} not found.<br> &nbsp; &nbsp;at /home/back4app/scm/back4app-cli-server/node_modules/parse-cli-server/lib/ParseCliController.js:114:17<br> &nbsp; &nbsp;at process._tickDomainCallback (internal/process/next_tick.js:129:7)\n"

This line throws the error https://github.com/back4app/parse-cli-server/blob/master/src/ParseCliController.js#L110

`{
	"folder":"cloud",
	"filename":"accurate_background.js",
	"version":"2",
	"checksum":"72dc1d6094ed88d2eae4b9c2d23749b6"
}`

**Comment by iurisilvio** [comment]
Thanks for your report. The server checksum was wrong for files with special chars like accents.

We did a quick fix and it should work now.

https://github.com/back4app/parse-cli-server/commit/14397e04c8e7229c0fa94ed0f11026775803d693
https://github.com/nodejs/node/issues/8853

Let me know if it works for you.
